version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Tcp9DOTJV9jZO7TdN3VvcneYiD
      MONGO_INITDB_DATABASE: chatapp
    volumes:
          - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
          - "./data:/data/db"
    command: mongod --auth
